# Generated by Django 3.2.6 on 2021-08-23 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('n0temail', '0002_alter_email_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
